# Site settings
title: Jekyll Doc Theme
email: russray2008@gmail.com 
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
#git_address: https://github.com/aksakalli/jekyll-doc-theme
#git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/New_York
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/russray2008"
  resume_twitter_url:           "https://twitter.com/russray2008?lang=en"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/russell.a.ray.3"
  resume_linkedin_url:          "https://www.linkedin.com/in/russellaray/"
  resume_instagram_url:         "https://www.instagram.com/russray2008/" 
resume_print_social_links:      true