# Site settings
title: Russell ("Russ") A. Ray
email: russray2008@gmail.com 
description:
  My journey from concept to reality on what it takes to build a static web site.
  All of my adventures are the discoveries I made along the way of launching the website.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clouddeveloper.net"  # the base hostname & protocol for your site, e.g. http://example.com  localhost:4000
git_address: https://github.com/russray2008/clouddeveloper.net
linkedin_address: https://www.linkedin.com/in/russellaray/
twitter_address: https://twitter.com/russray2008?lang=en
git_edit_address: https://github.com/russray2008/clouddeveloper.net

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - s3_website.yml
  
timezone: America/New_York

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

   

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/russray2008"
  resume_twitter_url:           "https://twitter.com/russray2008?lang=en"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/russell.a.ray.3"
  resume_linkedin_url:          "https://www.linkedin.com/in/russellaray/"
  resume_instagram_url:         "https://www.instagram.com/russray2008/" 
resume_print_social_links:      true